### ISSUE TITLE
should be able to sort the questions 

### ISSUE THREAD

**Issue by dippas** [aioobe/stackrating#2]
While there is sort by user with a pagination, there is missing a question's sort within that user's page.  Either is a rating sort or by date.

**Comment by aioobe** [comment]
This is would be a nice feature. I'll take it into consideration for the next version.

**Comment by dippas** [comment]
How are you on this feature given its been more than 2 years?

**Comment by aioobe** [comment]
Stackrating is getting _very_ little traction unfortunately. Not a prioritized project for me. Patches are welcome though.
