### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by RinkAttendant6** [aioobe/stackrating#4]
[Stack Exchange only permits HTTPS image URLs](https://meta.stackexchange.com/q/291947/227404) as part of their plan to move to HTTPS. StackRating will need to support HTTPS in order for the badges to continue working.

If necessary, free TLS certificates can be obtained using [Let's Encrypt](https://letsencrypt.org/).

In addition it would be awesome to have coordinate with the community, perhaps on Meta Stack Exchange, to assist with updating the existing images to HTTPS.

**Comment by aioobe** [comment]
Thanks @RinkAttendant6.

SSL support added in commit https://github.com/aioobe/stackrating/commit/ac33d3a27a232e30a7c52b0c23b3995f7bd4927f

Changes are live with certificates from Let's Encrypt.

Will post on meta to see if a bulk update could be arranged.
